stages:
  - compile
  - test

before_script:
  - export CI_HOME="$( pwd )"
  - git config --global user.name 'CERN CI'
  - git config --global user.email 'joosep.pata@cern.ch'
  - git config --global user.github jpata
  - git submodule update --init --recursive
  - export CMSSW_GIT_REFERENCE="/cvmfs/cms.cern.ch/cmssw.git.daily"
  - export SCRAM_ARCH="slc6_amd64_gcc530"
  - export CMSSW_VERSION="CMSSW_8_0_25"
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - source /cvmfs/grid.cern.ch/emi-ui-3.15.3-1_sl6v1/etc/profile.d/setup-ui-example.sh
  - cd ..
  - scramv1 project CMSSW $CMSSW_VERSION
  - cd $CMSSW_VERSION/src
  - eval `scramv1 runtime -sh`
  - source $CI_HOME/setenv_sklearn_cmssw.sh
  - scram setup $CI_HOME/MEIntegratorStandalone/deps/gsl.xml
  - cd $CI_HOME
  - echo "${KRB_PASSWORD}" | kinit ${KRB_USERNAME}@CERN.CH
  - scp -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GSSAPIDelegateCredentials=yes -o GSSAPITrustDNS=yes -o GSSAPIAuthentication=yes -o ControlMaster=auto -o ControlPath=/tmp/%%r@%%h:%%p -o ControlPersist=1 {$KRB_USERNAME}@lxplus:~/x509 $CI_HOME/x509
  - export X509_USER_PROXY=$CI_HOME/x509
  - voms-proxy-info -d

compile:
  stage: compile
  script:
    - cd $CMSSW_BASE/src
    - eval `scramv1 runtime -sh`
    - git cms-init
    - git cms-merge-topic -u jpata:vhbbHeppy80X_heppy_fixes_march14
    - cp -r $CI_HOME TTH
    - cp -R TTH/MEIntegratorStandalone/libs/* $CMSSW_BASE/lib/$SCRAM_ARCH/
    - scram b
    - cd $CMSSW_BASE
    - find src -maxdepth 3 -type d | grep -e "^src/.*/.*/\(interface\|data\|python\|gc\)" | tar -czf $CI_HOME/cmssw.tgz lib biglib bin --exclude="*.pyc" --files-from -
  artifacts:
    paths:
      - cmssw.tgz
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 10 minutes

test_MEAnalysis_ttH:
  stage: test
  script:
    - cd $CMSSW_BASE
    - tar -xzf $CI_HOME/cmssw.tgz
    - cd src
    - scram b python
    - cd $CI_HOME
    - python $CMSSW_BASE/src/TTH/MEAnalysis/python/test_MEAnalysis_heppy.py --sample_pattern "ttHTobb*" | tee -i MEAnalysis_ttH.txt
  artifacts:
    paths:
      - MEAnalysis_ttH.txt
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

test_MEAnalysis_ttjets:
  stage: test
  script:
    - cd $CMSSW_BASE
    - tar -xzf $CI_HOME/cmssw.tgz
    - cd src
    - scram b python
    - cd $CI_HOME
    - python $CMSSW_BASE/src/TTH/MEAnalysis/python/test_MEAnalysis_heppy.py --sample_pattern "TT_TuneCUETP8M2T4_13TeV-powheg-pythia8" | tee -i MEAnalysis_ttjets.txt
  artifacts:
    paths:
      - MEAnalysis_ttjets.txt
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

test_MEAnalysis_DoubleMuon:
  stage: test
  script:
    - cd $CMSSW_BASE
    - tar -xzf $CI_HOME/cmssw.tgz
    - cd src
    - scram b python
    - cd $CI_HOME
    - python $CMSSW_BASE/src/TTH/MEAnalysis/python/test_MEAnalysis_heppy.py --sample_pattern "DoubleMuon" | tee -i MEAnalysis_DoubleMuon.txt
  artifacts:
    paths:
      - MEAnalysis_DoubleMuon.txt
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
