stages:
  - compile
  - test
  - test_sparsinator

before_script:
  - source /cvmfs/grid.cern.ch/etc/profile.d/setup-cvmfs-ui.sh
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - export CI_HOME="$( pwd )"
  - git config --global user.name 'CERN CI'
  - git config --global user.email 'joosep.pata@cern.ch'
  - git config --global user.github jpata
  - git submodule update --init --recursive
  - export CMSSW_GIT_REFERENCE="/cvmfs/cms.cern.ch/cmssw.git.daily"
  - export SCRAM_ARCH="slc6_amd64_gcc630"
  - export CMSSW_VERSION="CMSSW_9_4_2"
  - cd ..
  - cd $CI_HOME
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config
  - echo "${KRB_PASSWORD}" | kinit -f ${KRB_USERNAME}@CERN.CH
  - klist
  - scp -v -o StrictHostKeyChecking=no ${KRB_USERNAME}@lxplus.cern.ch:~/x509 ~/x509
  - export X509_USER_PROXY=~/x509
  - voms-proxy-info --all
  - ls -al

compile:
  stage: compile
  script:
    - cd $CI_HOME/..
    - rm -Rf $CMSSW_VERSION
    - scramv1 project CMSSW $CMSSW_VERSION
    - ls -al
    - cd $CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - git cms-init
    - git cms-merge-topic cms-nanoAOD:master
    - git cms-merge-topic kschweiger:HeppyttHbb_Jan12
    - git checkout -b nanoAOD cms-nanoAOD/master
    - cp -r $CI_HOME TTH
    - cp -R TTH/MEIntegratorStandalone/libs/* $CMSSW_BASE/lib/$SCRAM_ARCH/
    - scram setup $CI_HOME/MEIntegratorStandalone/deps/gsl.xml
    - scram b -j4
    - cd $CMSSW_BASE/..
    - tar -czf cmssw.tgz $CMSSW_VERSION
    - du -csh cmssw.tgz
    - mv $CI_HOME/../cmssw.tgz $CI_HOME 
  artifacts:
    paths:
      - cmssw.tgz
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

test_tth:
  stage: test
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    - cd $CMSSW_BASE/src/TTH/MEAnalysis
    - python python/test_MEAnalysis_heppy.py --sample ttHTobb_M125_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8
    - python test/validationHistos.py Loop_ttHTobb_M125_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8/tree.root
    - ls -al
    - tar -czf plots.tgz *.pdf Loop_ttHTobb_M125_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8/tree.root
    - du -csh plots.tgz
    - mv plots.tgz $CI_HOME/
  artifacts:
    paths:
      - plots.tgz
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

test_tth_sparsinator:
  stage: test_sparsinator
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    - cd $CMSSW_BASE/src/TTH
    - tar xfz "test_tth_${CI_BUILD_REF_NAME}.tgz"
    - ls -al

test_ttjets:
  stage: test
  script:
    - cd $CI_HOME/..
    - tar xfz $CI_HOME/cmssw.tgz
    - cd $CI_HOME/../$CMSSW_VERSION/src
    - eval `scramv1 runtime -sh`
    - cd $CI_HOME
    - cd $CMSSW_BASE/src/TTH/MEAnalysis
    - python python/test_MEAnalysis_heppy.py --sample TT_TuneCUETP8M2T4_13TeV-powheg-pythia8
    - python test/validationHistos.py Loop_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8
    - ls -al
    - tar -czf plots.tgz *.pdf
    - du -csh plots.tgz
    - mv plots.tgz $CI_HOME/
  artifacts:
    paths:
      - plots.tgz
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

