// 
// *  This file was automatically generated by MoMEMta-MaGMEE,
// *  A MadGraph Matrix Element Exporter plugin for MoMEMta.
// *
// *  It is subject to MoMEMta-MaGMEE's license and copyright:
// *
// *  Copyright (C) 2016  Universite catholique de Louvain (UCL), Belgium
// *
// *  This program is free software: you can redistribute it and/or modify
// *  it under the terms of the GNU General Public License as published by
// *  the Free Software Foundation, either version 3 of the License, or
// *  (at your option) any later version.
// *
// *  This program is distributed in the hope that it will be useful,
// *  but WITHOUT ANY WARRANTY; without even the implied warranty of
// *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// *  GNU General Public License for more details.
// *
// *  You should have received a copy of the GNU General Public License
// *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
// 

#include <string> 
#include <utility> 
#include <vector> 
#include <map> 

#include <P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx.h> 
#include <HelAmps_VLF_Singlet_UFO.h> 

#include <momemta/ParameterSet.h> 
#include <momemta/SLHAReader.h> 

namespace ttH_FullyLeptonic_groupSubprocesses_VLF_Singlet_UFO 
{

//==========================================================================
// Class member functions for calculating the matrix elements for
// Process: g g > t t~ h WEIGHTED<=4 @1
// *   Decay: t > w+ b WEIGHTED<=2
// *     Decay: w+ > mu+ vm WEIGHTED<=2
// *   Decay: t~ > w- b~ WEIGHTED<=2
// *     Decay: w- > mu- vm~ WEIGHTED<=2
// *   Decay: h > b b~ WEIGHTED<=2
// Process: u u~ > t t~ h WEIGHTED<=4 @1
// *   Decay: t > w+ b WEIGHTED<=2
// *     Decay: w+ > mu+ vm WEIGHTED<=2
// *   Decay: t~ > w- b~ WEIGHTED<=2
// *     Decay: w- > mu- vm~ WEIGHTED<=2
// *   Decay: h > b b~ WEIGHTED<=2
// Process: c c~ > t t~ h WEIGHTED<=4 @1
// *   Decay: t > w+ b WEIGHTED<=2
// *     Decay: w+ > mu+ vm WEIGHTED<=2
// *   Decay: t~ > w- b~ WEIGHTED<=2
// *     Decay: w- > mu- vm~ WEIGHTED<=2
// *   Decay: h > b b~ WEIGHTED<=2
// Process: d d~ > t t~ h WEIGHTED<=4 @1
// *   Decay: t > w+ b WEIGHTED<=2
// *     Decay: w+ > mu+ vm WEIGHTED<=2
// *   Decay: t~ > w- b~ WEIGHTED<=2
// *     Decay: w- > mu- vm~ WEIGHTED<=2
// *   Decay: h > b b~ WEIGHTED<=2
// Process: s s~ > t t~ h WEIGHTED<=4 @1
// *   Decay: t > w+ b WEIGHTED<=2
// *     Decay: w+ > mu+ vm WEIGHTED<=2
// *   Decay: t~ > w- b~ WEIGHTED<=2
// *     Decay: w- > mu- vm~ WEIGHTED<=2
// *   Decay: h > b b~ WEIGHTED<=2

//--------------------------------------------------------------------------

// Initialize process.

P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx(const ParameterSet& configuration) 
{

  std::string param_card = configuration.get < std::string > ("card"); 
  params.reset(new Parameters_VLF_Singlet_UFO(SLHA::Reader(param_card))); 

  // Set external particle masses for this matrix element
  mME.push_back(std::ref(params->ZERO)); 
  mME.push_back(std::ref(params->ZERO)); 
  mME.push_back(std::ref(params->mdl_MMU)); 
  mME.push_back(std::ref(params->ZERO)); 
  mME.push_back(std::ref(params->mdl_MB)); 
  mME.push_back(std::ref(params->mdl_MMU)); 
  mME.push_back(std::ref(params->ZERO)); 
  mME.push_back(std::ref(params->mdl_MB)); 
  mME.push_back(std::ref(params->mdl_MB)); 
  mME.push_back(std::ref(params->mdl_MB)); 

  mapFinalStates[{-13, 14, 5, 13, -14, -5, 5, -5}] = 
  {
    {
      &P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_gg_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx, 
      false, 
      {
        std::make_pair(21, 21)
      }, 
      1024, 
      256
    }
    , 
    {
      &P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_uux_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx, 
      true, 
      {
        std::make_pair(2, -2)
      }, 
      1024, 
      36
    }
    , 
    {
      &P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_ccx_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx, 
      true, 
      {
        std::make_pair(4, -4)
      }, 
      1024, 
      36
    }
    , 
    {
      &P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_ddx_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx, 
      true, 
      {
        std::make_pair(1, -1)
      }, 
      1024, 
      36
    }
    , 
    {
      &P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_ssx_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx, 
      true, 
      {
        std::make_pair(3, -3)
      }, 
      1024, 
      36
    }
  }; 

}

void P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::resetHelicities() 
{
  for (auto& finalState: mapFinalStates)
  {
    for (auto& subProcess: finalState.second)
    {
      subProcess.resetHelicities(); 
    }
  }
}


//--------------------------------------------------------------------------
// Evaluate |M|^2, return a map of final states

std::map < std::pair < int, int > , double >
    P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::compute(const std::pair <
    std::vector<double> , std::vector<double> > &initialMomenta, const
    std::vector < std::pair < int, std::vector<double> > > &finalState)
{

  // Set initial particle momenta
  momenta[0] = (double * ) (&initialMomenta.first[0]); 
  momenta[1] = (double * ) (&initialMomenta.second[0]); 

  // Suppose final particles are passed in the "correct" order
  std::vector<int> selectedFinalState(10 - 2); 
  for (size_t index = 0; index < (10 - 2); index++ )
  {
    selectedFinalState[index] = finalState[index].first; 
    momenta[index + 2] = (double * ) (&finalState[index].second[0]); 
  }

  // Set the event specific parameters
  params->updateParameters(); 
  params->updateCouplings(); 

  // Initialise result object
  std::map < std::pair < int, int > , double > result; 

  // Define permutation
  int perm[10]; 
  for(int i = 0; i < 10; i++ )
  {
    perm[i] = i; 
  }

  for(auto &me: mapFinalStates[selectedFinalState])
  {

    double me_sum = 0; 
    double me_mirror_sum = 0; 

    for(int ihel = 0; ihel < 1024; ihel++ )
    {

      if(me.goodHel[ihel])
      {

        double sum = 0.; 
        calculate_wavefunctions(perm, helicities[ihel]); 
        double meTemp = me.callback( * this); 
        sum += meTemp; 
        me_sum += meTemp/me.denominator; 

        if(me.hasMirrorProcess)
        {
          perm[0] = 1; 
          perm[1] = 0; 
          // Calculate wavefunctions
          calculate_wavefunctions(perm, helicities[ihel]); 
          // Mirror back
          perm[0] = 0; 
          perm[1] = 1; 
          meTemp = me.callback( * this); 
          sum += meTemp; 
          me_mirror_sum += meTemp/me.denominator; 
        }

        if( !sum)
          me.goodHel[ihel] = false; 
      }
    }

    for (auto const &initialState: me.initialStates)
    {
      result[initialState] = me_sum; 
      if (me.hasMirrorProcess)
        result[std::make_pair(initialState.second, initialState.first)] =
            me_mirror_sum;
    }
  }


  return result; 
}

//==========================================================================
// Private class member functions

//--------------------------------------------------------------------------
// Evaluate |M|^2 for each subprocess

void P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::calculate_wavefunctions(const int perm[], const int hel[]) 
{
  // Calculate wavefunctions for all processes
  static std::complex<double> w[43][18]; 

  // Calculate all wavefunctions
  vxxxxx(&momenta[perm[0]][0], mME[0], hel[0], -1, w[0]); 
  vxxxxx(&momenta[perm[1]][0], mME[1], hel[1], -1, w[1]); 
  ixxxxx(&momenta[perm[2]][0], mME[2], hel[2], -1, w[2]); 
  oxxxxx(&momenta[perm[3]][0], mME[3], hel[3], +1, w[3]); 
  FFV2_3(w[2], w[3], params->GC_13, params->mdl_MW, params->mdl_WW, w[4]); 
  oxxxxx(&momenta[perm[4]][0], mME[4], hel[4], +1, w[5]); 
  FFV2_1(w[5], w[4], params->GC_64, params->mdl_MT, params->mdl_WT, w[6]); 
  oxxxxx(&momenta[perm[5]][0], mME[5], hel[5], +1, w[7]); 
  ixxxxx(&momenta[perm[6]][0], mME[6], hel[6], -1, w[8]); 
  FFV2_3(w[8], w[7], params->GC_13, params->mdl_MW, params->mdl_WW, w[9]); 
  ixxxxx(&momenta[perm[7]][0], mME[7], hel[7], -1, w[10]); 
  FFV2_2(w[10], w[9], params->GC_22, params->mdl_MT, params->mdl_WT, w[11]); 
  oxxxxx(&momenta[perm[8]][0], mME[8], hel[8], +1, w[12]); 
  ixxxxx(&momenta[perm[9]][0], mME[9], hel[9], -1, w[13]); 
  FFS1_2_3(w[13], w[12], params->GC_42, params->GC_42, params->mdl_MH,
      params->mdl_WH, w[14]);
  VVV1P0_1(w[0], w[1], params->GC_6, params->ZERO, params->ZERO, w[15]); 
  FFS1_2_1(w[6], w[14], params->GC_52, params->GC_52, params->mdl_MT,
      params->mdl_WT, w[16]);
  FFS1_2_2(w[11], w[14], params->GC_52, params->GC_52, params->mdl_MT,
      params->mdl_WT, w[17]);
  FFV1_1(w[6], w[0], params->GC_7, params->mdl_MT, params->mdl_WT, w[18]); 
  FFV1_2(w[11], w[1], params->GC_7, params->mdl_MT, params->mdl_WT, w[19]); 
  FFV1_2(w[11], w[0], params->GC_7, params->mdl_MT, params->mdl_WT, w[20]); 
  FFV1_1(w[6], w[1], params->GC_7, params->mdl_MT, params->mdl_WT, w[21]); 
  ixxxxx(&momenta[perm[0]][0], mME[0], hel[0], +1, w[22]); 
  oxxxxx(&momenta[perm[1]][0], mME[1], hel[1], -1, w[23]); 
  FFV1P0_3(w[22], w[23], params->GC_7, params->ZERO, params->ZERO, w[24]); 
  FFS1_2_2(w[22], w[14], params->GC_49, params->GC_49, params->mdl_MU,
      params->ZERO, w[25]);
  FFV1P0_3(w[11], w[6], params->GC_7, params->ZERO, params->ZERO, w[26]); 
  FFS1_2_1(w[23], w[14], params->GC_49, params->GC_49, params->mdl_MU,
      params->ZERO, w[27]);
  ixxxxx(&momenta[perm[0]][0], mME[0], hel[0], +1, w[28]); 
  oxxxxx(&momenta[perm[1]][0], mME[1], hel[1], -1, w[29]); 
  FFV1P0_3(w[28], w[29], params->GC_7, params->ZERO, params->ZERO, w[30]); 
  FFS1_2_2(w[28], w[14], params->GC_43, params->GC_43, params->mdl_MC,
      params->ZERO, w[31]);
  FFS1_2_1(w[29], w[14], params->GC_43, params->GC_43, params->mdl_MC,
      params->ZERO, w[32]);
  ixxxxx(&momenta[perm[0]][0], mME[0], hel[0], +1, w[33]); 
  oxxxxx(&momenta[perm[1]][0], mME[1], hel[1], -1, w[34]); 
  FFV1P0_3(w[33], w[34], params->GC_7, params->ZERO, params->ZERO, w[35]); 
  FFS1_2_2(w[33], w[14], params->GC_44, params->GC_44, params->mdl_MD,
      params->ZERO, w[36]);
  FFS1_2_1(w[34], w[14], params->GC_44, params->GC_44, params->mdl_MD,
      params->ZERO, w[37]);
  ixxxxx(&momenta[perm[0]][0], mME[0], hel[0], +1, w[38]); 
  oxxxxx(&momenta[perm[1]][0], mME[1], hel[1], -1, w[39]); 
  FFV1P0_3(w[38], w[39], params->GC_7, params->ZERO, params->ZERO, w[40]); 
  FFS1_2_2(w[38], w[14], params->GC_47, params->GC_47, params->mdl_MS,
      params->ZERO, w[41]);
  FFS1_2_1(w[39], w[14], params->GC_47, params->GC_47, params->mdl_MS,
      params->ZERO, w[42]);

  // Calculate all amplitudes
  // Amplitude(s) for diagram number 0
  FFV1_0(w[11], w[16], w[15], params->GC_7, amp[0]); 
  FFV1_0(w[17], w[6], w[15], params->GC_7, amp[1]); 
  FFS1_2_0(w[19], w[18], w[14], params->GC_52, params->GC_52, amp[2]); 
  FFV1_0(w[17], w[18], w[1], params->GC_7, amp[3]); 
  FFS1_2_0(w[20], w[21], w[14], params->GC_52, params->GC_52, amp[4]); 
  FFV1_0(w[20], w[16], w[1], params->GC_7, amp[5]); 
  FFV1_0(w[17], w[21], w[0], params->GC_7, amp[6]); 
  FFV1_0(w[19], w[16], w[0], params->GC_7, amp[7]); 
  FFV1_0(w[11], w[16], w[24], params->GC_7, amp[8]); 
  FFV1_0(w[17], w[6], w[24], params->GC_7, amp[9]); 
  FFV1_0(w[25], w[23], w[26], params->GC_7, amp[10]); 
  FFV1_0(w[22], w[27], w[26], params->GC_7, amp[11]); 
  FFV1_0(w[11], w[16], w[30], params->GC_7, amp[12]); 
  FFV1_0(w[17], w[6], w[30], params->GC_7, amp[13]); 
  FFV1_0(w[31], w[29], w[26], params->GC_7, amp[14]); 
  FFV1_0(w[28], w[32], w[26], params->GC_7, amp[15]); 
  FFV1_0(w[11], w[16], w[35], params->GC_7, amp[16]); 
  FFV1_0(w[17], w[6], w[35], params->GC_7, amp[17]); 
  FFV1_0(w[36], w[34], w[26], params->GC_7, amp[18]); 
  FFV1_0(w[33], w[37], w[26], params->GC_7, amp[19]); 
  FFV1_0(w[11], w[16], w[40], params->GC_7, amp[20]); 
  FFV1_0(w[17], w[6], w[40], params->GC_7, amp[21]); 
  FFV1_0(w[41], w[39], w[26], params->GC_7, amp[22]); 
  FFV1_0(w[38], w[42], w[26], params->GC_7, amp[23]); 

}
double P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_gg_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx() 
{

  static std::complex<double> ztemp; 
  static std::complex<double> jamp[2]; 
  // The color matrix
  static const double denom[2] = {1, 1}; 
  static const double cf[2][2] = {{16, -2}, {-2, 16}}; 

  // Calculate color flows
  static const std::complex<double> cI(0., 1.); 
  jamp[0] = +cI * amp[0] + cI * amp[1] - amp[2] - amp[3] - amp[7]; 
  jamp[1] = -cI * amp[0] - cI * amp[1] - amp[4] - amp[5] - amp[6]; 

  // Sum and square the color flows to get the matrix element
  double matrix = 0; 
  for(int i = 0; i < 2; i++ )
  {
    ztemp = 0.; 
    for(int j = 0; j < 2; j++ )
      ztemp = ztemp + cf[i][j] * jamp[j]; 
    matrix = matrix + real(ztemp * conj(jamp[i]))/denom[i]; 
  }

  return matrix; 
}

double P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_uux_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx() 
{

  static std::complex<double> ztemp; 
  static std::complex<double> jamp[2]; 
  // The color matrix
  static const double denom[2] = {1, 1}; 
  static const double cf[2][2] = {{27, 9}, {9, 27}}; 

  // Calculate color flows
  jamp[0] = +1./2. * (+1./3. * amp[8] + 1./3. * amp[9] + 1./3. * amp[10] +
      1./3. * amp[11]);
  jamp[1] = +1./2. * (-amp[8] - amp[9] - amp[10] - amp[11]); 

  // Sum and square the color flows to get the matrix element
  double matrix = 0; 
  for(int i = 0; i < 2; i++ )
  {
    ztemp = 0.; 
    for(int j = 0; j < 2; j++ )
      ztemp = ztemp + cf[i][j] * jamp[j]; 
    matrix = matrix + real(ztemp * conj(jamp[i]))/denom[i]; 
  }

  return matrix; 
}

double P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_ccx_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx() 
{

  static std::complex<double> ztemp; 
  static std::complex<double> jamp[2]; 
  // The color matrix
  static const double denom[2] = {1, 1}; 
  static const double cf[2][2] = {{27, 9}, {9, 27}}; 

  // Calculate color flows
  jamp[0] = +1./2. * (+1./3. * amp[12] + 1./3. * amp[13] + 1./3. * amp[14] +
      1./3. * amp[15]);
  jamp[1] = +1./2. * (-amp[12] - amp[13] - amp[14] - amp[15]); 

  // Sum and square the color flows to get the matrix element
  double matrix = 0; 
  for(int i = 0; i < 2; i++ )
  {
    ztemp = 0.; 
    for(int j = 0; j < 2; j++ )
      ztemp = ztemp + cf[i][j] * jamp[j]; 
    matrix = matrix + real(ztemp * conj(jamp[i]))/denom[i]; 
  }

  return matrix; 
}

double P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_ddx_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx() 
{

  static std::complex<double> ztemp; 
  static std::complex<double> jamp[2]; 
  // The color matrix
  static const double denom[2] = {1, 1}; 
  static const double cf[2][2] = {{27, 9}, {9, 27}}; 

  // Calculate color flows
  jamp[0] = +1./2. * (+1./3. * amp[16] + 1./3. * amp[17] + 1./3. * amp[18] +
      1./3. * amp[19]);
  jamp[1] = +1./2. * (-amp[16] - amp[17] - amp[18] - amp[19]); 

  // Sum and square the color flows to get the matrix element
  double matrix = 0; 
  for(int i = 0; i < 2; i++ )
  {
    ztemp = 0.; 
    for(int j = 0; j < 2; j++ )
      ztemp = ztemp + cf[i][j] * jamp[j]; 
    matrix = matrix + real(ztemp * conj(jamp[i]))/denom[i]; 
  }

  return matrix; 
}

double P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx::matrix_1_ssx_ttxh_t_wpb_wp_mupvm_tx_wmbx_wm_mumvmx_h_bbx() 
{

  static std::complex<double> ztemp; 
  static std::complex<double> jamp[2]; 
  // The color matrix
  static const double denom[2] = {1, 1}; 
  static const double cf[2][2] = {{27, 9}, {9, 27}}; 

  // Calculate color flows
  jamp[0] = +1./2. * (+1./3. * amp[20] + 1./3. * amp[21] + 1./3. * amp[22] +
      1./3. * amp[23]);
  jamp[1] = +1./2. * (-amp[20] - amp[21] - amp[22] - amp[23]); 

  // Sum and square the color flows to get the matrix element
  double matrix = 0; 
  for(int i = 0; i < 2; i++ )
  {
    ztemp = 0.; 
    for(int j = 0; j < 2; j++ )
      ztemp = ztemp + cf[i][j] * jamp[j]; 
    matrix = matrix + real(ztemp * conj(jamp[i]))/denom[i]; 
  }

  return matrix; 
}



}

// Register matrix element with MoMEMta
#include <momemta/MatrixElementFactory.h> 
REGISTER_MATRIX_ELEMENT("ttH_FullyLeptonic_groupSubprocesses_VLF_Singlet_UFO_P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx", ttH_FullyLeptonic_groupSubprocesses_VLF_Singlet_UFO::P1_Sigma_VLF_Singlet_UFO_gg_mupvmbmumvmxbxbbx); 

